spring:
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/schema/schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database;MODE=MySQL
    username: test
    password:
    driver-class-name: org.h2.Driver