spring:
  config:
    activate:
      on-profile: local

  # console color
  output:
    ansi:
      enabled: always

  # datasource
  datasource:
    url: jdbc:h2:mem:database

  # sql init
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  # devtools
  devtools:
    restart:
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: trace
            StatementCreatorUtils: trace
          datasource:
            init: trace