###
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "name": "조현창",
  "date": "2025-01-01",
  "timeId": 1,
  "themeId": 1
}
###
GET http://localhost:8080/reservations
Accept: application/json

###
DELETE http://localhost:8080/reservations/1


###
POST http://localhost:8080/times
Content-Type: application/json

{
  "startAt": "10:00"
}

###
GET http://localhost:8080/times
Accept: application/json

###
DELETE http://localhost:8080/times/1

###
POST localhost:8080/themes HTTP/1.1
content-type: application/json

{
  "name": "레벨2 탈출",
  "description": "우테코 레벨2를 탈출하는 내용입니다.",
  "thumbnail": "https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg"
}

###
GET localhost:8080/themes HTTP/1.1

###
DELETE localhost:8080/themes/1