### 예약 생성
POST {{reservation-api}}/reservations
content-type: application/json; charset=UTF-8

{
  "scheduleId": 1,
  "themeId": 1,
  "date": "2022-08-11",
  "time": "13:00",
  "name": "name"
}

### 예약 조회
GET {{reservation-api}}/reservations?date=2022-08-11
content-type: application/json

### 예약 삭제
DELETE {{reservation-api}}/reservations?date=2022-08-11&time=13:00
