### 예약 등록
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "scheduleId": 1,
  "date": "2022-08-11",
  "time": "13:00",
  "name": "신지혜"
}

### 예약 조회
GET http://localhost:8080/reservations?date=2022-08-11

### 예약 삭제
DELETE http://localhost:8080/reservations?date=2022-08-11&time=13:00
Content-Type: application/json
