### 예약 생성
POST http://localhost:8080/reservations
Content-Type: application/json

{
  "date": "2022-08-11",
  "time": "13:00",
  "name": "name"
}

### 예약 조회
GET http://localhost:8080/reservations?date=2022-08-11
Content-Type: application/json

### 예약 삭제
DELETE http://localhost:8080/reservations?date=2022-08-11&time=13:00